create table tarefa (prioridade integer not null, realizado bit not null, id bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
INSERT INTO tarefa(nome, descricao, realizado, prioridade) VALUES ('Comprar ração', 'Ir na loja do centro', FALSE, 1);
INSERT INTO tarefa(nome, descricao, realizado, prioridade) VALUES ('Academia', 'Realizar treino de perna', TRUE, 2);
INSERT INTO tarefa(nome, descricao, realizado, prioridade) VALUES ('Entregar TCC', 'Terminar descrição das atividades', FALSE, 3);
INSERT INTO tarefa(nome, descricao, realizado, prioridade) VALUES ('Pagar conta', 'Ir na lotérica da Maria', TRUE, 3);
create table tarefa (prioridade integer not null, realizado bit not null, id bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
INSERT INTO tarefa(nome, descricao, realizado, prioridade) VALUES ('Comprar ração', 'Ir na loja do centro', FALSE, 1);
INSERT INTO tarefa(nome, descricao, realizado, prioridade) VALUES ('Academia', 'Realizar treino de perna', TRUE, 2);
INSERT INTO tarefa(nome, descricao, realizado, prioridade) VALUES ('Entregar TCC', 'Terminar descrição das atividades', FALSE, 3);
INSERT INTO tarefa(nome, descricao, realizado, prioridade) VALUES ('Pagar conta', 'Ir na lotérica da Maria', TRUE, 3);
create table tarefa (prioridade integer not null, realizado bit not null, id bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
INSERT INTO tarefa(nome, descricao, realizado, prioridade) VALUES ('Comprar ração', 'Ir na loja do centro', FALSE, 1);
INSERT INTO tarefa(nome, descricao, realizado, prioridade) VALUES ('Academia', 'Realizar treino de perna', TRUE, 2);
INSERT INTO tarefa(nome, descricao, realizado, prioridade) VALUES ('Entregar TCC', 'Terminar descrição das atividades', FALSE, 3);
INSERT INTO tarefa(nome, descricao, realizado, prioridade) VALUES ('Pagar conta', 'Ir na lotérica da Maria', TRUE, 3);
create table tarefa (prioridade integer not null, realizado bit not null, id bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
INSERT INTO tarefa(nome, descricao, realizado, prioridade) VALUES ('Comprar ração', 'Ir na loja do centro', FALSE, 1);
INSERT INTO tarefa(nome, descricao, realizado, prioridade) VALUES ('Academia', 'Realizar treino de perna', TRUE, 2);
INSERT INTO tarefa(nome, descricao, realizado, prioridade) VALUES ('Entregar TCC', 'Terminar descrição das atividades', FALSE, 3);
INSERT INTO tarefa(nome, descricao, realizado, prioridade) VALUES ('Pagar conta', 'Ir na lotérica da Maria', TRUE, 3);
create table tarefa (prioridade integer not null, realizado bit not null, id bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
INSERT INTO tarefa(nome, descricao, realizado, prioridade) VALUES ('Comprar ração', 'Ir na loja do centro', FALSE, 1);
INSERT INTO tarefa(nome, descricao, realizado, prioridade) VALUES ('Academia', 'Realizar treino de perna', TRUE, 2);
INSERT INTO tarefa(nome, descricao, realizado, prioridade) VALUES ('Entregar TCC', 'Terminar descrição das atividades', FALSE, 3);
INSERT INTO tarefa(nome, descricao, realizado, prioridade) VALUES ('Pagar conta', 'Ir na lotérica da Maria', TRUE, 3);
create table tarefa (prioridade integer not null, realizado bit not null, id bigint not null auto_increment, descricao varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
INSERT INTO tarefa(nome, descricao, realizado, prioridade) VALUES ('Comprar ração', 'Ir na loja do centro', FALSE, 1);
INSERT INTO tarefa(nome, descricao, realizado, prioridade) VALUES ('Academia', 'Realizar treino de perna', TRUE, 2);
INSERT INTO tarefa(nome, descricao, realizado, prioridade) VALUES ('Entregar TCC', 'Terminar descrição das atividades', FALSE, 3);
INSERT INTO tarefa(nome, descricao, realizado, prioridade) VALUES ('Pagar conta', 'Ir na lotérica da Maria', TRUE, 3);
